apiVersion: config.kubernetes.io/v1
kind: ResourceList
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress
    spec:
      rules:
        - host: "sub.${DOMAIN:-domain.com}"
  - apiVersion: v1
    kind: Service
    metadata:
      name: service
    spec:
      ports:
        - name: http
          port: ${PORT:number}
functionConfig:
  kind: VariableReplacer
  metadata:
    name: variable-injector
    annotations:
      config.kubernetes.io/function: |
        container:
          image: ghcr.io/choffmeister/kustomize-variable-injector:latest
      config.kubernetes.io/local-config: 'true'
  replacements:
    - target:
        kind: Ingress
      variables:
        DOMAIN: mydomain.com
    - target:
        kind: Service
      variables:
        PORT: 8080
