apiVersion: choffmeister.github.com/v1alpha1
kind: VariableReplacer
metadata:
  name: variable-injector
  annotations:
    config.kubernetes.io/function: |
      container:
        image: ghcr.io/choffmeister/kustomize-variable-injector:latest
values:
  DOMAIN: mydomain.com
